### ISSUE TITLE
Runtime typecheck needed for Piezo

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#171]
We need to check that the correct types are passed at runtime:
```
>>> r.power_board.piezo.buzz(1,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dan/Code/j5/j5/components/piezo.py", line 80, in buzz
    self._backend.buzz(self._board, self._identifier, duration, pitch)
  File "/home/dan/Code/j5/j5/backends/hardware/sr/v4/power_board.py", line 247, in buzz
    duration_ms = round(duration / timedelta(milliseconds=1))
TypeError: unsupported operand type(s) for /: 'int' and 'datetime.timedelta'
```

**Comment by trickeydan** [comment]
@HU90m I feel like you might want this one?

**Comment by trickeydan** [comment]
This was actually done in https://github.com/j5api/j5/commit/657d2cc892d7f8b15292184fba4b381b0167668d
