### ISSUE TITLE
Investigate strange exception in MB tests

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#394]
```
tests/backends/hardware/sr/v4/test_motor_board.py .......Exception ignored in: <function SRV4MotorBoardHardwareBackend.__del__ at 0x7fa76805a8c0>
Traceback (most recent call last):
  File "/home/dan/Code/sro/j5/j5/backends/hardware/sr/v4/motor_board.py", line 94, in __del__
    self.set_motor_state(i, MotorSpecialState.BRAKE)
  File "/home/dan/Code/sro/j5/j5/backends/backend.py", line 32, in new_method
    retval = old_method(*args, **kwargs)
  File "/home/dan/Code/sro/j5/j5/backends/hardware/sr/v4/motor_board.py", line 153, in set_motor_state
    self.send_command(CMD_MOTOR[identifier], value)
  File "/home/dan/Code/sro/j5/j5/backends/hardware/j5/serial.py", line 34, in catch_exceptions
    return func(*args, **kwargs)
  File "/home/dan/Code/sro/j5/j5/backends/hardware/sr/v4/motor_board.py", line 108, in send_command
    "Mismatch in command bytes written to serial interface.",
j5.backends.backend.CommunicationError: Mismatch in command bytes written to serial interface.
```

**Comment by kierdavis** [comment]
Huh, I've never noticed this error message in the source code before, let alone at runtime. Apparently it occurs when we try to write data to the serial port but not all bytes get written (maybe because the serial write buffer is full?). Isn't this normally handled by trying to write the remaining data again?

**Comment by trickeydan** [comment]
This can be replicated by running `pytest -s tests`

**Comment by trickeydan** [comment]
I believe this bug is related to the crashes that don't stop the motors turning :o
